// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "<Pending>", Scope = "member", Target = "~M:EnterpriseDB.EDBClient.Json.NET.Internal.JsonNetJsonConverter.GetSize(System.Boolean,EnterpriseDB.EDBClient.Internal.SizeContext,System.Type,Newtonsoft.Json.JsonSerializerSettings,System.Text.Encoding,System.Object,System.Object@)~EnterpriseDB.EDBClient.Internal.Size")]
[assembly: SuppressMessage("AOT", "IL3050:Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.", Justification = "<Pending>", Scope = "member", Target = "~M:EnterpriseDB.EDBClient.Json.NET.Internal.JsonNetJsonConverter.GetSize(System.Boolean,EnterpriseDB.EDBClient.Internal.SizeContext,System.Type,Newtonsoft.Json.JsonSerializerSettings,System.Text.Encoding,System.Object,System.Object@)~EnterpriseDB.EDBClient.Internal.Size")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "<Pending>", Scope = "member", Target = "~M:EnterpriseDB.EDBClient.Json.NET.Internal.JsonNetJsonConverter.Read(System.Boolean,System.Boolean,EnterpriseDB.EDBClient.Internal.PgReader,System.Type,Newtonsoft.Json.JsonSerializerSettings,System.Text.Encoding,System.Threading.CancellationToken)~System.Threading.Tasks.ValueTask{System.Object}")]
[assembly: SuppressMessage("AOT", "IL3050:Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.", Justification = "<Pending>", Scope = "member", Target = "~M:EnterpriseDB.EDBClient.Json.NET.Internal.JsonNetJsonConverter.Read(System.Boolean,System.Boolean,EnterpriseDB.EDBClient.Internal.PgReader,System.Type,Newtonsoft.Json.JsonSerializerSettings,System.Text.Encoding,System.Threading.CancellationToken)~System.Threading.Tasks.ValueTask{System.Object}")]
