namespace EnterpriseDB.EDBClient.EntityFrameworkCore.PostgreSQL.Query;

public class TPCFiltersInheritanceQueryNpgsqlTest(TPCFiltersInheritanceQueryNpgsqlFixture fixture)
    : TPCFiltersInheritanceQueryTestBase<TPCFiltersInheritanceQueryNpgsqlFixture>(fixture);
