name: BlackDuck-Source-Binaries-Scan

env:
  CLOUDSMITH_REPO: "dev"
  DOTNET_VERSION: "6.0.2.1"
  
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  #schedule:
    # Runs at 00:00 on day-of-month 1.
    #- cron: '0 0 1 * *'

jobs:
  blackduck-scan:
    name: blackduck-scan-job
    runs-on: self-hosted
    steps:
      - name: Checkout source repo
        uses: actions/checkout@master
        with:
         path: edb-dotnet

      - name: Set version with underscore
        run: |
          echo DOTNET_UNDERSCORE_VERSION=$(echo ${{env.DOTNET_VERSION}} | sed -e 's|\.|_|g') >> $GITHUB_ENV
          
#<<Same way clone all the other required source repositories if any >>

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@master
        with:
          repository: EnterpriseDB/edb-blackduck-scanner.git
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: .github/actions/edb-blackduck-scanner

      - name: Scan Sources and Binaries
        id: run_scan
        uses: ./.github/actions/edb-blackduck-scanner
        with:
 #         PPAS_VERSION: "${{env.PPAS_VERSION}}"
          PACKAGE_VERSION: "${{env.DOTNET_VERSION}}-1"
          CLOUDSMITH_TOKEN: "${{secrets.CLOUDSMITH_DEV_TOKEN}}"
          BLACKDUCK_SCRIPT_DIR: "edb-dotnet/.github/workflows/blackduck"
          BLACKDUCK_API_TOKEN: "${{secrets.BLACKDUCK_API_TOKEN}}"
          CLOUDSMITH_REPO_NAME: "${{env.CLOUDSMITH_REPO}}"
          CLOUDSMITH_ORGANIZATION: "enterprisedb"
          PACKAGES: "edb-dotnet"
          CLOUDSMITH_API_KEY: "${{secrets.CLOUDSMITH_API_KEY}}"
          COMPONENT: "edb-dotnet"
          BUILDS_SERVER_USER: ${{secrets.BUILDS_SERVER_USER}}
          BUILDS_SERVER_PASSWORD: ${{secrets.BUILDS_SERVER_PASSWORD}}
          WINDOWS_X64_STAGING_BINARIES_PATH: "https://builds.enterprisedb.com/builds/released-builds/PPAS/Updates/Connectors/Redux-Connectors/DNET/Windows64/6.0.2.1-1/20220728/StagingBinaries/dotnet/windows.zip"

      - if: steps.run_scan.outcome == 'success'
        name: Open Jira Ticket To Review Scan
        uses: bryannice/gitactions-jira-issue-creation@master
        env:
          JIRA_ACCOUNT_URL: https://enterprisedb.atlassian.net/
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
#         JIRA_ISSUE_ATTACHMENT: log_file.log
          JIRA_ISSUE_DESCRIPTION: https://enterprisedb.app.blackduck.com/api/search/project-versions?limit=25&offset=0&q=edb-dotnet
          JIRA_ISSUE_SUMMARY: Review JDBC ${{env.DOTNET_VERSION}} blackduck scan
          JIRA_ISSUE_TYPE: Story
          JIRA_PROJECT: EC
          JIRA_USERNAME: muhammad.aqeel@enterprisedb.com

      - if: steps.run_scan.outcome != 'success'
        name: Open Jira Ticket To Fix Failure
        uses: bryannice/gitactions-jira-issue-creation@master
        env:
          JIRA_ACCOUNT_URL: https://enterprisedb.atlassian.net/
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
#         JIRA_ISSUE_ATTACHMENT: log_file.log
          JIRA_ISSUE_DESCRIPTION: "https://github.com/EnterpriseDB/edbas/runs/${GITHUB_RUN_ID}"
          JIRA_ISSUE_SUMMARY: JDBC ${{env.DOTNET_VERSION}} Blackduck Scan Failed
          JIRA_ISSUE_TYPE: Story
          JIRA_PROJECT: EC
          JIRA_USERNAME: muhammad.aqeel@enterprisedb.com

      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_MESSAGE: 'DOTNET - ${{env.DOTNET_VERSION}} blackduck scan finsihed from github action. https://enterprisedb.app.blackduck.com/api/projects/45e8b4e7-0402-4522-810a-85e31d22b609?offset=0&limit=100'
      #     SLACK_TITLE: 'DOTNET - ${{env.DOTNET_VERSION}} BlackDuck Signature and Binary Scan'
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
  generate-pdf-report:
    name: generate-report-job
    needs: blackduck-scan
    runs-on: self-hosted
    steps:
      - name: Checkout source repo
        uses: actions/checkout@master

      - name: Set version with underscore
        run: |
          echo DOTNET_UNDERSCORE_VERSION=$(echo ${{env.DOTNET_VERSION}} | sed -e 's|\.|_|g') >> $GITHUB_ENV
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@master
        with:
          repository: EnterpriseDB/blackduck_pdf_report_generator.git
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: .github/actions/blackduck_pdf_report_generator

      - name: Generate PDF Report
        uses: ./.github/actions/blackduck_pdf_report_generator
        with:
          PRODUCT_NAME: "EDB-DOTNET"
          PRODUCT_LONG_NAME: "EDB DOTNET"
          PRODUCT_VERSION: "${{env.DOTNET_VERSION}}"
          PDF_REPORT_NAME: "dotnet_${{env.DOTNET_UNDERSCORE_VERSION}}.pdf"
          BLACKDUCK_API_TOKEN: "${{secrets.BLACKDUCK_API_TOKEN}}"

      - name: Upload packages to artifactory
        uses: actions/upload-artifact@v2
        with:
          name: dotnet_${{env.DOTNET_UNDERSCORE_VERSION}}.pdf
          path: dotnet_${{env.DOTNET_UNDERSCORE_VERSION}}.pdf

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@master
        with:
          repository: EnterpriseDB/edb-s3-copy.git
          ref: master
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: .github/actions/edb-s3-copy

      - name: Copy PDF Report to S3
        uses: ./.github/actions/edb-s3-copy
        with:
          AWS_ACCESS_KEY_ID: "${{secrets.PLATFORM_SERVICES_S3_ACCESS_KEY_ID}}"
          AWS_SECRET_ACCESS_KEY: "${{secrets.PLATFORM_SERVICES_S3_SECRET_ACCESS_KEY}}"
          SOURCE: "dotnet_${{env.DOTNET_UNDERSCORE_VERSION}}.pdf"
          RECURSIVE: "false"
          AWS_S3_BUCKET: "platform-services-builds-and-logs"
          S3_BUCKET_PATH: "/blackduck/dotnet/${{env.DOTNET_VERSION}}/dotnet_${{env.DOTNET_UNDERSCORE_VERSION}}.pdf"
          AWS_REGION: "us-east-1"

     # - name: Slack Notification
     #  uses: rtCamp/action-slack-notify@v2
     #   env:
     #     SLACK_MESSAGE: 'jdbc_${{env.JDBC_UNDERSCORE_VERSION}}.pdf copied to https://platform-services-builds-and-logs.s3.amazonaws.com/blackduck/jdbc/${{env.JDBC_VERSION}}/jdbc_${{env.JDBC_UNDERSCORE_VERSION}}.pdf'
     #     SLACK_TITLE: 'EDB JDBC BlackDuck PDF Report'
     #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}   
