###
# Foundation-security Trufflehog workflow
# version: 2.3
###
name: Foundation-Security/Trufflehog Scan

on:
  push:
    tags:
      - "**"
    branches:
      - "*main*"
      - "*master*"
      - "*STABLE*"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      base:
        description: "Start scanning from this base commit/branch"
        required: false
        default: ""
      head:
        description: "Scan commits until this head commit/branch"
        required: true
        default: ""

jobs:
  Trufflehog-Scan:
    name: TruffleHog Scan Job
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source repository
        id: checkout-source
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: source
          fetch-depth: 0
          token: ${{ secrets.GH_SLONIK }}

      - name: Checkout foundation-security repository
        id: checkout-foundation-security
        uses: actions/checkout@v4
        with:
          repository: EnterpriseDB/foundation-security
          ref: v2
          path: foundation-security
          token: ${{ secrets.GH_SLONIK }}

      - name: Secrets Scan
        id: call-th-composite
        uses: ./foundation-security/actions/trufflehog
        with:
          cloudsmith-token: ${{ secrets.CLOUDSMITH_READ_ALL }}
          github-token: ${{ secrets.GH_SLONIK }}
          slack-token: ${{ secrets.SLONIK_SLACK_BOT_TOKEN }}
          head: ${{ github.event.inputs.head }}
          base: ${{ github.event.inputs.base }}
